<center><h1>DSCI 552: Machine Learning for Data Science</h1></center><br>
<center>Time Series Classification</center>

<h3>Homework 3</h3>
<p></p>
<b><span>Name: Sri Manvith Vaddeboyina</span></b><br>
<b><span>USC ID: 1231409457</span></b><br>
<b><span>Github username: srimanvithv</span></b>

## 1. Time Series Classification Part 1: Feature Creation/Extraction

### (a) Download Data

Package imports

In [58]:
import os
import re
import pandas as pd
import numpy as np
from scipy.stats import bootstrap
pd.set_option('display.max_colwidth', None)

Get the AReM Data Set

Download the AReM data from:<br>
https://archive.ics.uci.edu/ml/datasets/Activity+Recognition+system+based+on+Multisensor+data+fusion+\%28AReM\%29 <br><br>
The dataset contains 7 folders that represent seven types of activities. In
each folder, there are multiple files each of which represents an instant of a human
performing an activity. Each file containis 6 time series collected from activities of the same person, which are called avg_rss12, var_rss12, avg_rss13, var_rss13, vg_rss23, and ar_rss23. There are 88 instances in the dataset, each of which contains 6 time series and each time series has 480 consecutive values.

In [59]:
def load_and_preprocess_csv(file_path):
    if file_path == '../data/AReM/bending2/dataset4.csv':
        df = pd.read_csv(file_path, skiprows = 5,usecols = [1, 2, 3, 4, 5, 6],names=['avg_rss12', 'var_rss12', 'avg_rss13', 'var_rss13', 'avg_rss23', 'var_rss23'], delim_whitespace = True) 

    else:
        df = pd.read_csv(file_path, skiprows = 4, usecols = [1, 2, 3, 4, 5, 6])

    return df

def load_files_in_directory(directory_path):
    files = {}
    for root, dirs, filenames in os.walk(directory_path):
        for filename in filenames:
            if filename.endswith('.csv'):
                file_path = os.path.join(root, filename)
                df = load_and_preprocess_csv(file_path)
                if df is not None:
                    files[file_path] = df
    return files

data_folder_path = '../data/AReM/'
files = load_files_in_directory(data_folder_path)

### (b) Test and Train Data

In [60]:
root = "../data/AReM"

train_dfs = {}
test_dfs = {}

files_ = [os.path.join(root_path, file_name) 
         for root_path, _, files in os.walk(root) 
         for file_name in files 
         if not file_name.endswith('.pdf')]

train_files = [fp for fp in files_
         if (('bending1' in fp or 'bending2' in fp) and any(dataset in fp for dataset in ['dataset1.csv', 'dataset2.csv']))
         or (not any(dataset in fp for dataset in ['dataset1.csv', 'dataset2.csv']) and not ('bending1' in fp or 'bending2' in fp))]

test_files = [fp for fp in files_ if fp not in train_files]



for file_path in train_files:
    if file_path == '../data/AReM/bending2/dataset4.csv':
        df = pd.read_csv(file_path, skiprows = 5,usecols = [1, 2, 3, 4, 5, 6],names=['avg_rss12', 'var_rss12', 'avg_rss13', 'var_rss13', 'avg_rss23', 'var_rss23'], delim_whitespace = True) 
    else:
        df = pd.read_csv(file_path, skiprows = 4, usecols = [1, 2, 3, 4, 5, 6])
        
    train_dfs[file_path] = df

for file_path in test_files:
    if file_path == '../data/AReM/bending2/dataset4.csv':
        df = pd.read_csv(file_path, skiprows = 5,usecols = [1, 2, 3, 4, 5, 6],names=['avg_rss12', 'var_rss12', 'avg_rss13', 'var_rss13', 'avg_rss23', 'var_rss23'], delim_whitespace = True) 
    else:
        df = pd.read_csv(file_path, skiprows = 4, usecols = [1, 2, 3, 4, 5, 6])    
    test_dfs[file_path] = df
    
print('\033[1mTraining set size: ',len(train_files))
print('\033[1mTesting set size: ',len(test_files))

Training set size:  69
Testing set size:  19

### (c) Feature Extraction

#### i. Research

The time-domain features that are usually used in time series classification are: 
- <b>Mean</b>
- <b>Median</b>
- <b>Minimum</b>
- <b>Maximum</b>
- <b>Standard Deviation</b>
- <b>Variance</b>
- <b>Skewness</b>
- <b>Kurtosis</b>
- <b>Quantiles</b>
- <b>Range</b>
- <b>Interquartile Range (IQR)</b>

#### ii. Extraction

In [61]:
def extract(files_list):
    features = ['min', 'max', 'mean', '50%', 'std', '25%', '75%']

    time_series_statistical_features = ['min', 'max', 'mean', 'median', 'standard deviation', '1st quart', '3rd quart']

    data_list = []
    instance_column = list(range(1, len(files_list) + 1))

    for file_df in files_list.values():
        statistics = file_df.describe()
        feature_data = [statistics[feature][param] for feature in file_df.columns for param in features]
        data_list.append([len(data_list) + 1] + feature_data)

    columns = ['Instance'] + [f"{param}_{i+1}" for i in range(len(files[list(files.keys())[0]].columns)) for param in time_series_statistical_features]
    dataset = pd.DataFrame(data_list, columns = columns)
    dataset['Instance'] = instance_column
    
    return dataset

In [62]:
print("\033[1mComplete Dataset:")
complete_dataset_summary = extract(files)
display(complete_dataset_summary)

Complete Dataset:

,Instance,min_1,max_1,mean_1,median_1,standard deviation_1,1st quart_1,3rd quart_1,min_2,max_2,...,standard deviation_5,1st quart_5,3rd quart_5,min_6,max_6,mean_6,median_6,standard deviation_6,1st quart_6,3rd quart_6
0,1,36.25,48.00,43.969125,44.50,1.618364,43.3100,44.67,0.0,1.50,...,3.318301,20.5000,23.7500,0.0,2.96,0.555313,0.490,0.487826,0.0000,0.8300
1,2,37.00,48.00,43.454958,43.25,1.386098,42.5000,45.00,0.0,1.58,...,2.488862,22.2500,24.0000,0.0,5.26,0.679646,0.500,0.622534,0.4300,0.8700
2,3,33.00,47.75,42.179813,43.50,3.670666,39.1500,45.00,0.0,3.00,...,3.849448,30.4575,36.3300,0.0,2.18,0.613521,0.500,0.524317,0.0000,1.0000
3,4,33.00,45.75,41.678063,41.75,2.243490,41.3300,42.75,0.0,2.83,...,2.411026,28.4575,31.2500,0.0,1.79,0.383292,0.430,0.389164,0.0000,0.5000
4,5,37.25,45.00,40.624792,40.50,1.476967,39.2500,42.00,0.0,1.30,...,2.188449,33.0000,36.0000,0.0,1.92,0.570583,0.430,0.582915,0.0000,1.3000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,84,18.50,44.25,35.752354,36.00,4.614802,33.0000,39.33,0.0,12.60,...,3.120057,14.0000,18.0625,0.0,9.39,3.069667,2.770,1.748326,1.7975,4.0600
84,85,24.25,45.00,37.177042,36.25,3.581301,34.5000,40.25,0.0,8.58,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.9000
85,86,23.33,43.50,36.244083,36.75,3.822016,33.4575,39.25,0.0,9.71,...,3.617702,15.7500,21.0000,0.0,11.15,3.530500,3.110,1.963685,2.1700,4.6175
86,87,26.25,44.25,36.957458,36.29,3.434863,34.5000,40.25,0.0,8.64,...,2.851673,14.0000,18.2500,0.0,8.34,2.934625,2.525,1.631380,1.6600,4.0300
87,88,27.75,44.67,37.144833,36.33,3.758904,34.0000,40.50,0.0,10.76,...,2.689291,15.0000,18.7500,0.0,8.75,2.822437,2.590,1.637183,1.5800,3.7400

In [63]:
print("\033[1mTrain Dataset:")
train_dataset_summary = extract(train_dfs)
display(train_dataset_summary)

Train Dataset:

,Instance,min_1,max_1,mean_1,median_1,standard deviation_1,1st quart_1,3rd quart_1,min_2,max_2,...,standard deviation_5,1st quart_5,3rd quart_5,min_6,max_6,mean_6,median_6,standard deviation_6,1st quart_6,3rd quart_6
0,1,37.25,45.00,40.624792,40.50,1.476967,39.2500,42.0000,0.0,1.30,...,2.188449,33.0000,36.0000,0.0,1.92,0.570583,0.430,0.582915,0.0000,1.3000
1,2,38.00,45.67,42.812812,42.50,1.435550,42.0000,43.6700,0.0,1.22,...,1.995255,32.0000,34.5000,0.0,3.11,0.571083,0.430,0.601010,0.0000,1.3000
2,3,18.33,47.67,34.333042,34.75,4.948770,31.2500,38.0000,0.0,12.48,...,3.000493,13.7500,18.0000,0.0,8.01,3.261583,2.980,1.617290,2.0500,4.3200
3,4,21.50,51.00,34.935813,35.50,4.645944,32.0000,38.0625,0.0,12.21,...,3.192058,14.2375,18.2500,0.0,10.21,3.280021,3.015,1.700918,2.1200,4.5000
4,5,18.00,46.00,35.193333,36.00,4.751868,32.0000,38.7500,0.0,16.20,...,3.207642,14.2500,18.5000,0.0,8.50,3.241958,3.015,1.769182,1.8850,4.4400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64,65,18.50,44.25,35.752354,36.00,4.614802,33.0000,39.3300,0.0,12.60,...,3.120057,14.0000,18.0625,0.0,9.39,3.069667,2.770,1.748326,1.7975,4.0600
65,66,24.25,45.00,37.177042,36.25,3.581301,34.5000,40.2500,0.0,8.58,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.9000
66,67,23.33,43.50,36.244083,36.75,3.822016,33.4575,39.2500,0.0,9.71,...,3.617702,15.7500,21.0000,0.0,11.15,3.530500,3.110,1.963685,2.1700,4.6175
67,68,26.25,44.25,36.957458,36.29,3.434863,34.5000,40.2500,0.0,8.64,...,2.851673,14.0000,18.2500,0.0,8.34,2.934625,2.525,1.631380,1.6600,4.0300
68,69,27.75,44.67,37.144833,36.33,3.758904,34.0000,40.5000,0.0,10.76,...,2.689291,15.0000,18.7500,0.0,8.75,2.822437,2.590,1.637183,1.5800,3.7400

In [64]:
print("\033[1mTest Dataset:")
test_dataset_summary = extract(test_dfs)
display(test_dataset_summary)

Test Dataset:

,Instance,min_1,max_1,mean_1,median_1,standard deviation_1,1st quart_1,3rd quart_1,min_2,max_2,...,standard deviation_5,1st quart_5,3rd quart_5,min_6,max_6,mean_6,median_6,standard deviation_6,1st quart_6,3rd quart_6
0,1,36.25,48.00,43.969125,44.500,1.618364,43.3100,44.6700,0.0,1.50,...,3.318301,20.5000,23.7500,0.0,2.96,0.555313,0.490,0.487826,0.0000,0.830
1,2,37.00,48.00,43.454958,43.250,1.386098,42.5000,45.0000,0.0,1.58,...,2.488862,22.2500,24.0000,0.0,5.26,0.679646,0.500,0.622534,0.4300,0.870
2,3,33.00,47.75,42.179813,43.500,3.670666,39.1500,45.0000,0.0,3.00,...,3.849448,30.4575,36.3300,0.0,2.18,0.613521,0.500,0.524317,0.0000,1.000
3,4,33.00,45.75,41.678063,41.750,2.243490,41.3300,42.7500,0.0,2.83,...,2.411026,28.4575,31.2500,0.0,1.79,0.383292,0.430,0.389164,0.0000,0.500
4,5,35.00,47.40,43.954500,44.330,1.558835,43.0000,45.0000,0.0,1.70,...,1.999604,35.3625,36.5000,0.0,1.79,0.493292,0.430,0.513506,0.0000,0.940
5,6,19.33,43.50,34.227771,35.500,4.889576,30.5000,37.7500,0.0,14.50,...,3.092094,14.7500,18.6700,0.0,9.74,3.394125,3.100,1.792090,2.1050,4.425
6,7,12.50,45.00,33.509729,34.125,4.850923,30.5000,36.7500,0.0,13.05,...,3.133564,14.6275,18.7500,0.0,8.96,3.378479,3.085,1.787360,2.0600,4.440
7,8,25.00,47.50,31.058250,29.710,4.829794,27.5000,31.8125,0.0,6.38,...,7.853427,9.0000,18.3125,0.0,4.92,1.098104,0.940,0.831480,0.5000,1.300
8,9,27.50,33.00,29.881938,30.000,1.153837,29.0000,30.2700,0.0,1.00,...,1.745970,17.0000,19.0000,0.0,6.40,0.701625,0.710,0.481103,0.4700,0.940
9,10,19.00,45.50,30.938104,29.000,7.684146,26.7500,38.0000,0.0,6.40,...,5.845911,15.0000,20.8125,0.0,6.73,1.107354,0.830,1.080842,0.4700,1.300
10,11,21.00,50.00,32.586208,33.000,6.238143,26.1875,34.5000,0.0,9.90,...,5.032424,17.6700,23.5000,0.0,13.61,1.162042,0.830,1.332980,0.4700,1.300
11,12,33.33,48.00,44.334729,45.000,2.476940,42.2500,46.5000,0.0,3.90,...,5.401794,9.3300,17.7500,0.0,5.02,0.933000,0.830,0.673609,0.4700,1.250
12,13,35.50,46.25,43.174938,43.670,1.989052,42.5000,44.5000,0.0,2.12,...,2.983976,12.7500,16.5000,0.0,5.72,0.911979,0.830,0.666161,0.4700,1.220
13,14,33.25,48.00,42.363563,43.000,2.068247,42.0000,43.5000,0.0,4.44,...,4.956821,10.1875,17.6900,0.0,6.02,1.034021,0.830,0.985627,0.4700,1.250
14,15,37.00,50.75,45.917667,45.635,1.089027,45.0000,46.5000,0.0,4.87,...,3.585511,16.5000,21.0000,0.0,7.22,0.904604,0.710,0.896171,0.4300,1.120
15,16,23.50,30.00,27.716375,27.500,1.442253,27.0000,29.0000,0.0,1.79,...,4.074511,5.5000,10.7500,0.0,4.50,0.734271,0.710,0.613688,0.4300,1.000
16,17,24.75,48.33,44.182937,48.000,7.495615,48.0000,48.0000,0.0,3.11,...,3.274539,2.0000,5.5425,0.0,3.91,0.692771,0.500,0.675781,0.3225,0.940
17,18,24.25,45.00,37.177042,36.250,3.581301,34.5000,40.2500,0.0,8.58,...,2.890347,17.9500,21.7500,0.0,9.34,2.921729,2.500,1.852600,1.5000,3.900
18,19,28.75,44.75,37.561188,36.875,3.226507,35.2500,40.2500,0.0,9.91,...,2.727377,18.0000,21.5000,0.0,9.62,2.765896,2.450,1.769203,1.4100,3.770

#### iii. Standard Deviation

In [65]:
std_complete_dataset = pd.DataFrame({'Feature': complete_dataset_summary.drop(columns=['Instance']).std().index, 'Standard Deviation': complete_dataset_summary.drop(columns=['Instance']).std().values})
print("\033[1mComplete Dataset:")
std_complete_dataset

Complete Dataset:

                 Feature  Standard Deviation
0                  min_1            9.569975
1                  max_1            4.394362
2                 mean_1            5.335718
3               median_1            5.440054
4   standard deviation_1            1.772153
5            1st quart_1            6.153590
6            3rd quart_1            5.138925
7                  min_2            0.000000
8                  max_2            5.062729
9                 mean_2            1.574164
10              median_2            1.412244
11  standard deviation_2            0.884105
12           1st quart_2            0.946386
13           3rd quart_2            2.125266
14                 min_3            2.956462
15                 max_3            4.875137
16                mean_3            4.008380
17              median_3            4.036396
18  standard deviation_3            0.946710
19           1st quart_3            4.220658
20           3rd quart_3            4.171628
21                 min_4            0.000000
22                 max_4            2.183625
23                mean_4            1.166114
24              median_4            1.145586
25  standard deviation_4            0.458242
26           1st quart_4            0.843620
27           3rd quart_4            1.552504
28                 min_5            6.124001
29                 max_5            5.741238
30                mean_5            5.675593
31              median_5            5.813782
32  standard deviation_5            1.024898
33           1st quart_5            6.096465
34           3rd quart_5            5.531720
35                 min_6            0.045838
36                 max_6            2.518921
37                mean_6            1.154812
38              median_6            1.086474
39  standard deviation_6            0.517617
40           1st quart_6            0.758584
41           3rd quart_6            1.523599

In [66]:
std_train_dataset = pd.DataFrame({'Feature': train_dataset_summary.drop(columns=['Instance']).std().index, 'Standard Deviation': train_dataset_summary.drop(columns=['Instance']).std().values})
print("\033[1mTrain Dataset:")
std_train_dataset

Train Dataset:

                 Feature  Standard Deviation
0                  min_1           10.159024
1                  max_1            4.173422
2                 mean_1            5.174888
3               median_1            5.129112
4   standard deviation_1            1.670654
5            1st quart_1            5.848703
6            3rd quart_1            4.961361
7                  min_2            0.000000
8                  max_2            5.291956
9                 mean_2            1.633793
10              median_2            1.469024
11  standard deviation_2            0.927242
12           1st quart_2            0.969995
13           3rd quart_2            2.204254
14                 min_3            3.000350
15                 max_3            4.691128
16                mean_3            3.916841
17              median_3            3.885534
18  standard deviation_3            0.823376
19           1st quart_3            4.179802
20           3rd quart_3            4.050169
21                 min_4            0.000000
22                 max_4            2.236511
23                mean_4            1.201199
24              median_4            1.169348
25  standard deviation_4            0.483574
26           1st quart_4            0.863708
27           3rd quart_4            1.601099
28                 min_5            5.084531
29                 max_5            4.552150
30                mean_5            4.727677
31              median_5            4.826417
32  standard deviation_5            0.851842
33           1st quart_5            5.122077
34           3rd quart_5            4.657274
35                 min_6            0.051766
36                 max_6            2.342180
37                mean_6            1.183808
38              median_6            1.119038
39  standard deviation_6            0.520259
40           1st quart_6            0.774014
41           3rd quart_6            1.562880

In [67]:
std_test_dataset = pd.DataFrame({'Feature': test_dataset_summary.drop(columns=['Instance']).std().index, 'Standard Deviation': test_dataset_summary.drop(columns=['Instance']).std().values})
print("\033[1mTest Dataset:")
std_test_dataset

Test Dataset:

                 Feature  Standard Deviation
0                  min_1            7.222177
1                  max_1            5.246515
2                 mean_1            6.008040
3               median_1            6.603260
4   standard deviation_1            2.113653
5            1st quart_1            7.321472
6            3rd quart_1            5.834827
7                  min_2            0.000000
8                  max_2            4.092546
9                 mean_2            1.274075
10              median_2            1.139638
11  standard deviation_2            0.676499
12           1st quart_2            0.827448
13           3rd quart_2            1.709264
14                 min_3            2.862658
15                 max_3            5.403553
16                mean_3            4.385331
17              median_3            4.601434
18  standard deviation_3            1.277961
19           1st quart_3            4.455735
20           3rd quart_3            4.605729
21                 min_4            0.000000
22                 max_4            2.029993
23                mean_4            1.018374
24              median_4            1.036695
25  standard deviation_4            0.356233
26           1st quart_4            0.760055
27           3rd quart_4            1.353641
28                 min_5            8.446869
29                 max_5            7.521073
30                mean_5            7.738397
31              median_5            8.053602
32  standard deviation_5            1.513730
33           1st quart_5            8.331674
34           3rd quart_5            7.492447
35                 min_6            0.000000
36                 max_6            3.123440
37                mean_6            1.001089
38              median_6            0.910254
39  standard deviation_6            0.508266
40           1st quart_6            0.648006
41           3rd quart_6            1.314630

In [74]:
confidence_interval = [
    [col, complete_dataset_summary[col].std(), bootstrap((complete_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.low, bootstrap((complete_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.high]
    for col in complete_dataset_summary.columns]

bootstrap_complete_dataset_summary = pd.DataFrame(confidence_interval, columns=['Feature Name', 'Standard Deviation', 'Lower Bound', 'Upper Bound'])[1:]
print("\033[1mComplete Dataset:")
bootstrap_complete_dataset_summary

Complete Dataset:

            Feature Name  Standard Deviation  Lower Bound  Upper Bound
1                  min_1            9.569975     8.217348    10.704231
2                  max_1            4.394362     3.306005     5.269063
3                 mean_1            5.335718     4.675214     5.837115
4               median_1            5.440054     4.760294     5.964649
5   standard deviation_1            1.772153     1.562763     1.935570
6            1st quart_1            6.153590     5.542312     6.603819
7            3rd quart_1            5.138925     4.308947     5.806972
8                  min_2            0.000000     0.000000     0.000000
9                  max_2            5.062729     4.595134     5.377385
10                mean_2            1.574164     1.393100     1.698068
11              median_2            1.412244     1.234108     1.536296
12  standard deviation_2            0.884105     0.799442     0.937724
13           1st quart_2            0.946386     0.828219     1.030619
14           3rd quart_2            2.125266     1.889331     2.285161
15                 min_3            2.956462     2.747467     3.092855
16                 max_3            4.875137     4.156789     5.432534
17                mean_3            4.008380     3.400360     4.467957
18              median_3            4.036396     3.409364     4.507903
19  standard deviation_3            0.946710     0.758431     1.112665
20           1st quart_3            4.220658     3.614282     4.675851
21           3rd quart_3            4.171628     3.520758     4.665291
22                 min_4            0.000000     0.000000     0.000000
23                 max_4            2.183625     1.966400     2.348672
24                mean_4            1.166114     1.070142     1.214927
25              median_4            1.145586     1.048463     1.194232
26  standard deviation_4            0.458242     0.419692     0.484057
27           1st quart_4            0.843620     0.771418     0.885540
28           3rd quart_4            1.552504     1.425058     1.617372
29                 min_5            6.124001     4.388667     7.450334
30                 max_5            5.741238     4.708362     6.535202
31                mean_5            5.675593     4.406769     6.676398
32              median_5            5.813782     4.490701     6.849665
33  standard deviation_5            1.024898     0.805579     1.211904
34           1st quart_5            6.096465     4.775856     7.144836
35           3rd quart_5            5.531720     4.340708     6.477835
36                 min_6            0.045838     0.000000     0.078029
37                 max_6            2.518921     2.236611     2.747931
38                mean_6            1.154812     1.057520     1.207692
39              median_6            1.086474     0.990880     1.141548
40  standard deviation_6            0.517617     0.476871     0.541945
41           1st quart_6            0.758584     0.686914     0.803298
42           3rd quart_6            1.523599     1.395869     1.591175

In [75]:
confidence_interval = [
    [col, train_dataset_summary[col].std(), bootstrap((train_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.low, bootstrap((train_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.high]
    for col in train_dataset_summary.columns]

bootstrap_train_dataset_summary = pd.DataFrame(confidence_interval, columns=['Feature Name', 'Standard Deviation', 'Lower Bound', 'Upper Bound'])[1:]
print("\033[1mTrain Dataset:")
bootstrap_train_dataset_summary

Train Dataset:

            Feature Name  Standard Deviation  Lower Bound  Upper Bound
1                  min_1           10.159024     8.544839    11.464846
2                  max_1            4.173422     3.005125     5.114447
3                 mean_1            5.174888     4.376780     5.803656
4               median_1            5.129112     4.327876     5.771497
5   standard deviation_1            1.670654     1.484530     1.797964
6            1st quart_1            5.848703     5.145062     6.374454
7            3rd quart_1            4.961361     3.961670     5.764098
8                  min_2            0.000000     0.000000     0.000000
9                  max_2            5.291956     4.794605     5.603977
10                mean_2            1.633793     1.438557     1.746071
11              median_2            1.469024     1.278043     1.588667
12  standard deviation_2            0.927242     0.838968     0.974124
13           1st quart_2            0.969995     0.842491     1.050822
14           3rd quart_2            2.204254     1.951980     2.346894
15                 min_3            3.000350     2.759000     3.137994
16                 max_3            4.691128     3.821919     5.332795
17                mean_3            3.916841     3.219574     4.417731
18              median_3            3.885534     3.181934     4.400696
19  standard deviation_3            0.823376     0.693059     0.920922
20           1st quart_3            4.179802     3.474733     4.688663
21           3rd quart_3            4.050169     3.310875     4.593706
22                 min_4            0.000000     0.000000     0.000000
23                 max_4            2.236511     1.990931     2.410546
24                mean_4            1.201199     1.105203     1.240728
25              median_4            1.169348     1.074873     1.207352
26  standard deviation_4            0.483574     0.440887     0.508562
27           1st quart_4            0.863708     0.788357     0.902252
28           3rd quart_4            1.601099     1.474980     1.653104
29                 min_5            5.084531     2.953306     6.571470
30                 max_5            4.552150     3.452263     5.423643
31                mean_5            4.727677     3.334966     5.869178
32              median_5            4.826417     3.409856     5.989657
33  standard deviation_5            0.851842     0.668224     0.999355
34           1st quart_5            5.122077     3.653765     6.320277
35           3rd quart_5            4.657274     3.388763     5.712043
36                 min_6            0.051766     0.000000     0.087690
37                 max_6            2.342180     2.093539     2.516342
38                mean_6            1.183808     1.084868     1.227859
39              median_6            1.119038     1.020823     1.167905
40  standard deviation_6            0.520259     0.477555     0.543665
41           1st quart_6            0.774014     0.699945     0.813790
42           3rd quart_6            1.562880     1.434034     1.619011

In [76]:
confidence_interval = [
    [col, test_dataset_summary[col].std(), bootstrap((test_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.low, bootstrap((test_dataset_summary[col],), np.std, confidence_level=0.9, random_state=1, method='percentile').confidence_interval.high]
    for col in test_dataset_summary.columns]

bootstrap_test_dataset_summary = pd.DataFrame(confidence_interval, columns=['Feature Name', 'Standard Deviation', 'Lower Bound', 'Upper Bound'])[1:]
print("\033[1mTest Dataset:")
bootstrap_test_dataset_summary

Test Dataset:

            Feature Name  Standard Deviation  Lower Bound  Upper Bound
1                  min_1            7.222177     5.284411     8.254804
2                  max_1            5.246515     1.749643     6.877701
3                 mean_1            6.008040     4.689778     6.510243
4               median_1            6.603260     5.122367     7.207522
5   standard deviation_1            2.113653     1.427676     2.429368
6            1st quart_1            7.321472     5.836990     7.890389
7            3rd quart_1            5.834827     4.170275     6.619694
8                  min_2            0.000000     0.000000     0.000000
9                  max_2            4.092546     2.715392     4.781584
10                mean_2            1.274075     0.555097     1.605825
11              median_2            1.139638     0.437986     1.458032
12  standard deviation_2            0.676499     0.388987     0.812498
13           1st quart_2            0.827448     0.376050     1.042706
14           3rd quart_2            1.709264     0.763429     2.145611
15                 min_3            2.862658     2.206842     3.150276
16                 max_3            5.403553     3.760623     6.229695
17                mean_3            4.385331     2.873305     5.179746
18              median_3            4.601434     3.024529     5.451350
19  standard deviation_3            1.277961     0.657828     1.639582
20           1st quart_3            4.455735     3.026071     5.233514
21           3rd quart_3            4.605729     2.938745     5.470314
22                 min_4            0.000000     0.000000     0.000000
23                 max_4            2.029993     1.442822     2.322291
24                mean_4            1.018374     0.587391     1.182078
25              median_4            1.036695     0.590478     1.207612
26  standard deviation_4            0.356233     0.225156     0.409102
27           1st quart_4            0.760055     0.469246     0.885283
28           3rd quart_4            1.353641     0.782871     1.570018
29                 min_5            8.446869     5.025720    10.259729
30                 max_5            7.521073     5.553422     8.624483
31                mean_5            7.738397     4.933081     9.266427
32              median_5            8.053602     5.070422     9.678723
33  standard deviation_5            1.513730     0.921712     1.873507
34           1st quart_5            8.331674     5.474757     9.909209
35           3rd quart_5            7.492447     4.634056     9.112908
36                 min_6            0.000000     0.000000     0.000000
37                 max_6            3.123440     2.124068     3.722031
38                mean_6            1.001089     0.612375     1.168708
39              median_6            0.910254     0.558449     1.071856
40  standard deviation_6            0.508266     0.354477     0.569279
41           1st quart_6            0.648006     0.384524     0.774717
42           3rd quart_6            1.314630     0.779134     1.531385

#### iv. Select Features

Mean <br>
Max <br>
3rd quartile

#

## 2. ISLR 3.7.4

I collect a set of data (n = 100 observations) containing a single predictor and a quantitative response. I then fit a linear regression model to the data, as well as a separate cubic regression, i.e. <br>
<center>Y = β<sub>0</sub> + β<sub>1</sub>X + β<sub>2</sub>$X^2$ + β<sub>3</sub>$X^3$ + ε<center>

### (a) Linear Train

<b>(a) Suppose that the true relationship between X and Y is linear, i.e. Y = β0 + β1X + ε. Consider the training residual sum of squares (RSS) for the linear regression, and also the training RSS for the cubic regression. Would we expect one to be lower than the other, would we expect them to be the same, or is there not enough information to tell? Justify your answer.</b>

**Answer:** Since predictors are directly proportional to the fitting of the model, the RSS for linear regression would be higher as compared to the RSS for cubic regression since cubic regression has more predictors and thus would ideally have a better fit on a regression model.

### (b) Linear Test

<b>(b) Answer (a) using test rather than training RSS.<b>

**Answer:** More predictors generally leads to overfitting using the test data. So, for the test case, the RSS for linear regression will be lower since it is more likely to provide relatively correct regression result.

### (c) Not Linear Train

<b>(c) Suppose that the true relationship between X and Y is not linear, but we don’t know how far it is from linear. Consider the training RSS for the linear regression, and also the training RSS for the cubic regression. Would we expect one to be lower than the other, would we expect them to be the same, or is there not enough information to tell? Justify your answer.</b>

**Answer:** The fundamental principle does not change. More predictors lead to less RSS and hence, the RSS for cubic would be less. Cubic regression has more flexibility.

### (d) Not Linear Testing

<b>(d) Answer (c) using test rather than training RSS.</b>

**Answer:** The information provided is insufficient as the answer will depend on the finding of which regression is the actual answer closer to.

<center><b>Thank You</b></center>